[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain_voting = "EEDxZUNCWebntLkRVJtsVWFCHamrJPcmuEnRDXCnHzLb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm vitest run"
